name: Deploy master
on:
  create
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout source code
      run: | 
        echo "hello poc-crate"
        run echo "jsonBody["ref"].ToString().Split('/').Last()"
